### PR TITLE
Make sure spacing between elements in body content is 40px

### PR DESCRIPTION
**Pull request by hqhhuang**
Bug/issue #, if applicable: 91070521

## Summary
Make sure the spacing between elements is 40px.
Fixes issue where when Asides are shown, the spacing is 2rem (34px).

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests - NA
- [x] Ran `npm test`, and it succeeded
- [ ] Updated documentation if necessary - NA

### CODE REVIEW

**Comment by hqhhuang** [comment]
@swift-ci test

**Review by dobromir-hristov — APPROVED** [review]
We cant use `rem(40px)`, because its declared after the vars, so this is not ideal, but its fine.

**Comment by hqhhuang** [comment]
Yup, that's exactly why I calculated the rem and hard coded it. I think we did this with a few other variables in this file as well.

**Comment by hqhhuang** [comment]
@swift-ci test

**Pull request merged**
