### PR TITLE
Prevents code listings inside questions to have border radius

### PR DESCRIPTION
**Pull request by marinaaisa**
Bug/issue #87742486, if applicable: 

## Summary

Prevents code listings inside questions to have border radius

Screenshot 2022-02-23 at 16 20 16

## Dependencies

NA

## Testing

Example fixture folder:
[manual-fixtures.zip](https://github.com/apple/swift-docc-render/files/8125486/manual-fixtures.zip)

Steps:
1. Use example attached above
2. Run VUE_APP_DEV_SERVER_PROXY=/path/to/manual-fixtures/ npm run serve
3. Go to http://localhost:8080/tutorials/technologyx/tutorial and scroll to "Check Your Understanding"
4. Select first option with code listing
5. Click Submit
6. Assert that there is no border radius cutting the content

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by marinaaisa** [comment]
@swift-ci test

**Comment by hqhhuang** [comment]
Hey Marina! The fix looks good to me, but I'm not able to reproduce the bug in this repo even without the change. Would this be better fixed in the internal repo?

**Review by hqhhuang — APPROVED** [review]

**Comment by mportiz08** [comment]
@swift-ci test

**Comment by mportiz08** [comment]
@swift-ci test

**Comment by mportiz08** [comment]
@swift-ci test

**Pull request merged**
