### PR TITLE
Opt-Click on framework name expand/collapse everything

### PR DESCRIPTION
**Pull request by marinaaisa**
Bug/issue #94150776, if applicable: 

## Summary

Opt-Click on framework name expand/collapse everything

## Dependencies

NA

## Testing

Steps:
1. Go to a framework name on the top of the page and click on it while
2. click on it while holding the opt key
3. Assert all symbols are toggled

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests
- [ ] Ran `npm test`, and it succeeded
- [ ] Updated documentation if necessary

### CODE REVIEW

**Comment by marinaaisa** [comment]
@swift-ci test

**Review by dobromir-hristov — COMMENTED** [review]
I think this is fine, but one thing I noticed is that if you have open items, it just alternates between opening and closing them. Which is kind of odd, it cannot force open/close all items.

**Comment by marinaaisa** [comment]
@swift-ci test

**Comment by marinaaisa** [comment]
> I think this is fine, but one thing I noticed is that if you have open items, it just alternates between opening and closing them. Which is kind of odd, it cannot force open/close all items.

I fixed it, please review again, thanks!

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Comment by marinaaisa** [comment]
@swift-ci test

**Review by dobromir-hristov — APPROVED** [review]
Works like a charm.

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Pull request merged**
