### PR TITLE
Use builtin image as fallback when authored image fails to load.

### PR DESCRIPTION
**Pull request by mportiz08**
Bug/issue #, if applicable: 83366845

## Summary

Updates the renderer to display the following image for the scenario where the image that an author has specified is not found or invalid for any reason.

Fallback image

## Testing

Steps:
1. Update an existing documentation catalog or source comment to include the following markdown:
```markdown
![blah](/fake/image/path.jpg)
```
2. Build this branch with `npm run build` and configure `DOCC_HTML_DIR=/path/to/swift-docc-render-dist` when previewing those docs with `docc preview`
3. Verify that the fallback image displays where the fake image markdown was added
4. Verify that real images still render as before

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [X] Added tests
- [X] Ran `npm test`, and it succeeded
- [X] Updated documentation if necessary

### CODE REVIEW

**Comment by mportiz08** [comment]
@swift-ci test

**Comment by marinaaisa** [comment]
Following your testing steps I tried adding `blah` to a markdown in an existing documentation and previewing it with DocC but I'm just getting an empty paragraph, no builtin image at all.
I'm getting a warning on docc `warning: Resource '/fake/image/path.jpg' couldn't be found` too.

Is there any chance I'm not triggering the error listener that you added on this PR? Do you suggest any other way to test this PR?
Thanks!

**Comment by mportiz08** [comment]
> Following your testing steps I tried adding `blah` to a markdown in an existing documentation and previewing it with DocC but I'm just getting an empty paragraph, no builtin image at all. I'm getting a warning on docc `warning: Resource '/fake/image/path.jpg' couldn't be found` too.
> 
> Is there any chance I'm not triggering the error listener that you added on this PR? Do you suggest any other way to test this PR? Thanks!

You're right. Those were bad testing instructions from me—sorry. You are correct that the DocC compiler will already warn when you reference an image not in the catalog and will omit the data for actually rendering the image entirely.

This scenario is actually more specific—these changes are for a situation where the image _did_ exist when the catalog was compiled but has since gone missing or is invalid now.

**Improved testing instructions:**

Option 1:

1. Use `docc preview` on an existing catalog that has an image.
2. With the server still running, manually delete the image asset (`rm /path/to/.docc-build/images/image`) and refresh the page.

Option 2:

1. Run `npm run serve` with an HTTP endpoint configured for `VUE_APP_DEV_SERVER_PROXY`
2. Utilize the Chrome web inspector to find a relevant image in the Network panel—right click on the image and use the "Block request URL" option to simulate an image that has been taken down from a server or is now unreachable. You can then refresh the page.

**Review by marinaaisa — APPROVED** [review]
Thanks for providing new testing steps. It looks good now :)

**Comment by marinaaisa** [comment]
✅ Screenshot 2022-01-26 at 15 33 40

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Comment by mportiz08** [comment]
@swift-ci test

**Pull request merged**
