### PR TITLE
Localnav without navigator should take up full space.

### PR DESCRIPTION
**Pull request by marinaaisa**
Bug/issue #103256123, if applicable: 

## Summary

1) Localnav without navigator should take up full space.
2) Localnav without navigator on mobile viewport should be correct without toggle button

### Before

Screenshot 2022-12-19 at 19 46 56

### After

Screenshot 2022-12-21 at 18 55 47

Screenshot 2022-12-19 at 19 44 59

## Dependencies

NA

## Testing

Steps:
1. Run a doccarchive without navigator
2. Assert that localnav takes full space

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by marinaaisa** [comment]
@swift-ci test

**Comment by marinaaisa** [comment]
@swift-ci test

**Review by mportiz08 — APPROVED** [review]
Looking good from my testing!

I'd appreciate if @dobromir-hristov could also review the code for an extra set of eyes.

**Review by dobromir-hristov — APPROVED** [review]
LGTM

**Comment by marinaaisa** [comment]
@swift-ci test

**Pull request merged**
