### PR TITLE
Fix selecting tags with the keyboard on Navigator

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Bug/issue #, if applicable: 90973785

## Summary

Fixes a bug with the tag selection, in the Navigator filter area.

## Dependencies

NA

## Testing

Steps:
1. Go to a page with a navigator
2. Click in the Navigator Filter and click `UP` arrow
3. Assert the first Tag is highlighted.
4. Make the viewport small
5. Open the navigator
6. Click in the Filter
7. Click `DOWN` arrow on keyboard
8. Assert the first tag is highlighted

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Review by hqhhuang — APPROVED** [review]
Looks good!

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Pull request merged**
