### PR TITLE
Fix regression with Objective-C api whitespace formatting

### PR DESCRIPTION
**Pull request by mportiz08**
Bug/issue #, if applicable: 109681482

## Summary

Fixes a regression that was introduced in #564 where multi-parameter Objective-C functions/initializers are not being formatted onto newlines anymore.

This happened because the code relies on a reference to a DOM node, and that PR introduced an additional layer of indirection where the reference is now a Vue component, requiring the need to also call `.$el` on that updated ref.

\cc @ethan-kusters 

## Testing

Steps:
1. Find any Objective-C symbol that has multiple parameters
2. Verify that the symbol is now being broken onto multiple lines instead of being on a single line

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [X] Added tests
- [X] Ran `npm test`, and it succeeded
- [X] Updated documentation if necessary

### CODE REVIEW

**Comment by mportiz08** [comment]
@swift-ci test

**Review by dobromir-hristov — APPROVED** [review]
🤦

**Review by marinaaisa — APPROVED** [review]
Oops 🫣

**Comment by mportiz08** [comment]
@swift-ci test

**Pull request merged**
