### PR TITLE
Simplify the matching pattern in the Navigator filter

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Bug/issue #, if applicable: 91443929

## Summary

This PR simplifies the filter matching pattern on the Navigator. Now it wont highlight leading/trailing spaces on potential matches.

**Old Behaviour:**

`FooBar` would match `FooBar` and `Foo Bar`.
`Foo` would match `Foo` and ` Foo `

**Now:**
`FooBar` matches only `FooBar`
`Foo` matches only `Foo`

Matches are case-insensitive, so casing doesnt matter much.

## Dependencies

NA

## Testing

Steps:
1. Serve using any archive with an index
2. Type in the filter input on the Navigator a single word
3. Assert only the word is highlighted as matching in the results.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Comment by biamx3** [comment]
Getting less matches for a query seems like a design regression. The original issue that needed a fix was just the highlighting of space before a word. For example, if a query is " help", the highlight should only be on top of "help", not the space. We should keep highlighting the space between two different words, like for example "foo bar".

**Comment by dobromir-hristov** [comment]
OK Let me explain a bit more. The matching pattern we had before would match a query with any spaces, no mater where and how much. So if I have `func help`, `funchel p` or `funchelp`, they would all match `func help` text. 
Because we match any number of spaces, between all the letters in the query, it was also highlighting the space before `help`, when just typing `help`.

My change removes that space ignoring, and tries to match what you typed.

**Before:**

image
image
image
image

**After**
image
image
image
image


**Alternative:**
If we really want to keep the old more relaxed matching, one other easy way to fix this would be to stop matching spaces before the first character of the query. This can be done in the `whiteSpaceIgnorantRegex` function, where we can just pass over the first char, if its not a `\`.

cc @mportiz08 @marinaaisa @hqhhuang

**Comment by biamx3** [comment]
Got it. I'm still concerned folks will accidentally type in an extra space or miss a space, so my preference is to go for the more forgiving previous matching. 

The second solution you described makes sense to me.

**Comment by dobromir-hristov** [comment]
Updated. @biamx3 @mportiz08 @hqhhuang give it another look.

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Review by hqhhuang — CHANGES_REQUESTED** [review]
Change looks good, I think we still need to fix a failing test in: `search-utils.spec.js`

**Comment by hqhhuang** [comment]
@swift-ci test

**Review by hqhhuang — APPROVED** [review]
LGTM, let's get @SamLanier and @biamx3 to review again before merging.

**Review by SamLanier — APPROVED** [review]
Design approved.

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Pull request merged**
