### PR TITLE
Do not open all items, if Hide Deprecated tag is picked

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Bug/issue #, if applicable: 93506254

## Summary

When "Hide Deprecated" tag is picked, the navigator should not go into filtering mode, opening every possible match.
It should only hide the deprecated items.

## Dependencies

NA

## Testing

Steps:
1. Use SlothCreator or any other archive with Deprecated items and visit any page
2. Assert that clicking on "Hide Deprecated" does not open all items
3. Assert that upon typing a filter keyword, all items are opened and upon removing that, they are back to normal.
4. Assert the current open page is highlighted in the navigator and all of it's parents are open so its visible

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by JCDiana** [comment]
> Bug/issue #, if applicable: 93506254
> 
> 
> 
> ## Summary
> 
> 
> 
> When "Hide Deprecated" tag is picked, the navigator should not go into filtering mode, opening every possible match.
> 
> It should only hide the deprecated items.
> 
> 
> 
> ## Dependencies
> 
> 
> 
> NA
> 
> 
> 
> ## Testing
> 
> 
> 
> Steps:
> 
> 1. Use SlothCreator or any other archive with Deprecated items and visit any page
> 
> 2. Assert that clicking on "Hide Deprecated" does not open all items
> 
> 3. Assert that upon typing a filter keyword, all items are opened and upon removing that, they are back to normal.
> 
> 4. Assert the current open page is highlighted in the navigator and all of it's parents are open so its visible
> 
> 
> 
> ## Checklist
> 
> 
> 
> Make sure you check off the following items. If they cannot be completed, provide a reason.
> 
> 
> 
> - [x] Added tests
> 
> - [x] Ran `npm test`, and it succeeded
> 
> - [x] Updated documentation if necessary
> 
>

**Review by marinaaisa — COMMENTED** [review]
1) In small viewports the tag "Hide deprecated" gets cut off when being selected. I'm pretty sure this is a regression from https://github.com/apple/swift-docc-render/pull/291
Do you want to fix it in this radar or want me to create a new one?

Screenshot 2022-05-30 at 17 16 08

2) When adding an input to filter input after selecting the "Hide deprecated" tags, the matching children don't get opened, is this intended? I thought we would keep it closed only when there was no input added.

Screenshot 2022-05-30 at 17 18 45

**Comment by JCDiana** [comment]
> 1) In small viewports the tag "Hide deprecated" gets cut off when being selected. I'm pretty sure this is a regression from https://github.com/apple/swift-docc-render/pull/291
> 
> Do you want to fix it in this radar or want me to create a new one?
> 
> 
> 
> Screenshot 2022-05-30 at 17 16 08
> 
> 
> 
> 2) When adding an input to filter input after selecting the "Hide deprecated" tags, the matching children don't get opened, is this intended? I thought we would keep it closed only when there was no input added.
> 
> 
> 
> Screenshot 2022-05-30 at 17 18 45

**Comment by dobromir-hristov** [comment]
1 sounds like its normal to get cutoff.
2 is a bug I will investigate.

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Pull request merged**
