### PR TITLE
Update Framework Icon 

### PR DESCRIPTION
**Pull request by hqhhuang**
Bug/issue #, if applicable: 91483033

## Summary
Remove the old hero icon and replace it with a new framework Icon.

## Testing
Verify if hero icon is the new design:
Screen Shot 2022-04-11 at 9 09 48 PM

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests - NA
- [x] Ran `npm test`, and it succeeded
- [ ] Updated documentation if necessary - NA

### CODE REVIEW

**Comment by hqhhuang** [comment]
@biamx3 Could you review the visuals?

**Comment by hqhhuang** [comment]
@swift-ci test

**Comment by dobromir-hristov** [comment]
This outright removes the module icon, I am OK with the change, as long as that was the intended design decision @biamx3

**Comment by biamx3** [comment]
> This outright removes the module icon, I am OK with the change, as long as that was the intended design decision @biamx3

The module icon is the one with the star, right? If so, then yes, we should remove it and keep this new one with the stacks.

**Comment by biamx3** [comment]
Tested it and looks good.

**Comment by hqhhuang** [comment]
> > This outright removes the module icon, I am OK with the change, as long as that was the intended design decision @biamx3
> 
> The module icon is the one with the star, right? If so, then yes, we should remove it and keep this new one with the stacks.

Yes, the topic module icon is the one with the star.

**Comment by hqhhuang** [comment]
@swift-ci test

**Review by dobromir-hristov — APPROVED** [review]

**Pull request merged**
