### PR TITLE
Remove `min-width` from web content container

### PR DESCRIPTION
**Pull request by hqhhuang**
Bug/issue #, if applicable: 95981164

## Summary
Remove `min-width` property from `breakpoint-dynamic-sidebar-content`; this change only affects the web. 

## Testing
Steps:
1. Inspect the body content `container` class in ContentTable, DocumentationTopic, and BetaLegalText; and `__content` class in DocumentationHero. Assert that no `min-width` property are applied.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests - NA
- [x] Ran `npm test`, and it succeeded
- [ ] Updated documentation if necessary - NA

### CODE REVIEW

**Comment by hqhhuang** [comment]
@swift-ci test

**Review by dobromir-hristov — APPROVED** [review]
LGTM. Can @SamLanier give it a look?

**Comment by SamLanier** [comment]
Design approved.

**Comment by hqhhuang** [comment]
@swift-ci test

**Pull request merged**
