### PR TITLE
Sidenav style updates

### PR DESCRIPTION
**Pull request by marinaaisa**
Bug/issue #90168484, #89558736, #89375818, if applicable: 

### Framework heading

When selected:

- [x] Background should be fill-tertiary
- [x] Text should be bold

When no selected:

- [x] Background should be fill-secondary
- [x] Text should be semibold

### Others sidenav specs:

- [x] Space between Framework heading and items should be 8px
- [x] Space between icon and text in each item should be 7px
- [x] We should no longer aim for a rounded radius.
- [x] Selected and hover state of items should span the full width of the sidebar.
- [x] The top level items in the sidebar should also be aligned with the top level technology title.
- [x] Delete NavigatorLeafIcon
- [x] Hover state for top level technology should be the same color as the rest of items

## Dependencies

NA

## Testing

Steps:
1. Run npm run serve with your documentation
2. Enable sidenav
3. Assert that summary list is correct

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests (Not needed)
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by marinaaisa** [comment]
I changed some of spacing to have more consistency trying to use `20px` and `10px` but since some of the design specs on rdar://90168484 (Search & Nav: Sidebar Polish) were having 7px I'm not sure if these are the right specs.

Screenshot 2022-03-24 at 18 31 00

@SamLanier feel free to send me the Sketch file and I will get the spacing from there :)

**Review by dobromir-hristov — COMMENTED** [review]
Changes look good to me. Going to wait for @SamLanier to approve the visuals.

**Review by SamLanier — APPROVED** [review]
Design approved.

**Comment by marinaaisa** [comment]
@swift-ci test

**Review by dobromir-hristov — APPROVED** [review]

**Comment by marinaaisa** [comment]
@swift-ci test

**Comment by marinaaisa** [comment]
@swift-ci test

**Pull request merged**
