### PR TITLE
[5.7] Plist links in topics section should not be in code voice

### PR DESCRIPTION
**Pull request by hqhhuang**
- Rationale: Plist links are being displayed in code voice in the topics section, which is misleading and inconsistent with how the same links are displayed on other sections of the page
- Risk: Low
- Risk Detail: Only affects plist links in the topic section; does not affect other types of pages.
- Reward: High
- Reward Details: Plist items will no longer be incorrectly displayed in code voice in the Topics section
- Original PR: https://github.com/apple/swift-docc-render/pull/390
- Issue: rdar://62751444
- Code Reviewed By: @mportiz08 
- Testing Details: Tested manually in the browser and added relevant unit tests

Note: dependency: https://github.com/apple/swift-docc-render/pull/388

### CODE REVIEW

**Comment by hqhhuang** [comment]
@swift-ci test

**Comment by hqhhuang** [comment]
@swift-ci test

**Comment by tAmasa** [comment]
@swift-ci test

**Comment by hqhhuang** [comment]
@swift-ci test

**Pull request merged**
