### PR TITLE
[5.7] Fix width of highlight in S viewport

### PR DESCRIPTION
**Pull request by hqhhuang**
- **Rationale:** Fixes a bug where api diff highlight box gets cut off in small viewport.
- **Risk:** Low
- **Risk Detail:** Just 1-liner CSS change
- **Reward:** High
- **Reward Details:** Fixes regression so the visual looks as intended.
- **Original PR:** https://github.com/apple/swift-docc-render/pull/178
- **Issue:** rdar://89800555
- **Code Reviewed By:** @dobromir-hristov 
- **Testing Details:** Manually tested in the browser.

### CODE REVIEW

**Comment by hqhhuang** [comment]
@swift-ci test

**Review by franklinsch — APPROVED** [review]

**Comment by hqhhuang** [comment]
@swift-ci test

**Comment by hqhhuang** [comment]
@swift-ci test

**Comment by hqhhuang** [comment]
@swift-ci test

**Comment by hqhhuang** [comment]
@swift-ci test

**Pull request merged**
