### PR TITLE
Disable `skip-nav` VO link in IDE

### PR DESCRIPTION
**Pull request by hqhhuang**
Bug/issue #, if applicable: rdar://108634054

## Summary
Disable `skip-nav` VO link in IDE

### CODE REVIEW

**Comment by hqhhuang** [comment]
@swift-ci test

**Review by dobromir-hristov — APPROVED** [review]

**Review by marinaaisa — APPROVED** [review]
🚀

**Comment by marinaaisa** [comment]
Hey @hqhhuang I opened a new radar for this PR: rdar://108649548

**Comment by hqhhuang** [comment]
@swift-ci test

**Pull request merged**
