### PR TITLE
Use the single-letter icon for namespace symbols in navigator

### PR DESCRIPTION
**Pull request by mportiz08**
Bug/issue #, if applicable: 120780967

## Summary

Updates configuration so that pages for C++ "namespace" symbols are rendered with a single-letter "N" icon in the navigator sidebar instead of a generic "article" icon.

**Example**

Screenshot 2024-02-15 at 12 46 37 PM

## Dependencies

apple/swift-docc#817

## Testing

Steps:
1. Checkout this branch of swift-docc-render and build it with `npm run build`
2. Checkout my branch of swift-docc from apple/swift-docc#817 and build it with `swift build`
3. Preview the example C++ doc catalog with `DOCC_HTML_DIR=/path/to/swift-docc-render/dist swift run docc preview Tests/SwiftDocCTests/Test\ Bundles/CxxSymbols.docc`
4. Open http://localhost:8080/documentation/cxxsymbols and verify that the `Foo` namespace in the navigator is using the "N" icon

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [X] Added tests (unit test for icon mappings are dynamically generated)
- [X] Ran `npm test`, and it succeeded
- [X] Updated documentation if necessary

\cc @daniel-grumberg

### CODE REVIEW

**Review by hqhhuang — COMMENTED** [review]
Looks good!
I find it a bit confusing that a page tagged with the `TechnologyIcon` has article style content instead of symbol style content though. Why don't we use a symbol icon with the letter `N` to represent namespace symbols?

**Comment by mportiz08** [comment]
> Looks good! I find it a bit confusing that a page tagged with the `TechnologyIcon` has article style content instead of symbol style content though. Why don't we use a symbol icon with the letter `N` to represent namespace symbols?

While a C++ namespace is technically categorized as a symbol by DocC, it conceptually represents a grouping of other symbols, most similar to a module in Swift, which we render with the generic "technology" icon.

**Review by hqhhuang — APPROVED** [review]

**Comment by mportiz08** [comment]
@daniel-grumberg suggested using the "N" icon as well, so I've changed it to that

**Comment by mportiz08** [comment]
@swift-ci test

**Review by eango — APPROVED** [review]
Tested and looking good; thanks @mportiz08

**Pull request merged**
