### PR TITLE
Prevent scrolling the page, when using the custom dropdown component

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Bug/issue #, if applicable:  86641543

## Summary

In latest Safari Technology Preview if you click on the Tutorial pages navigation dropdowns, you get scrolled to the top.

This is a result of us focusing items inside the dropdown, and the page trying to scroll to those items.

## Dependencies

NA

## Testing

Steps:
1. Use any docc archive with a tutorial in it
2. Open the tutorial page and one of the two dropdowns in the Navigation bar
3. Assert that the page does not scroll to the top, upon opening the dropdowns.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests - no need
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Review by mportiz08 — COMMENTED** [review]
Seems to work well, although I think this might indicate that the real problem is with the browser since the sticky nav is already in view and shouldn't need to be scrolled to the top of the page per-se.

I'm ok with taking this change as a workaround until the potential browser issue is resolved though.

Is there any reasonable update to the unit tests we can make to test this change do you think?

**Comment by dobromir-hristov** [comment]
> 

Yeah... I think its an issue with the version of Safari, just wanted to find some fix quick :/ I am OK with leaving this out until they fix it too :))

**Review by marinaaisa — APPROVED** [review]
It seems to work fine in Safari Technology Preview.
I suggest that we merge this as a way to fix it until the Safari team fixes it.
Thanks, Dobri :)

**Comment by mportiz08** [comment]
@swift-ci test

**Pull request merged**
