### PR TITLE
Change the tab-nav rendering to be v-show based

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Bug/issue #, if applicable: 108379797

## Summary

Changes the TabNav content rendering to be v-show based, so images can be pre-loaded and wont flash when changing tabs.

## Dependencies

NA

## Testing

1. Load an archive with a tabnav that has mostly images
2. Assert images no longer flash when changing active tab
 
## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by mportiz08** [comment]
Not opposed to switching to a `v-show` based approach as long as we've done some performance testing of realistic scenarios to make sure that there's no major regression with loading everything up-front.

**Comment by dobromir-hristov** [comment]
Played a bit with tabnavs with lots of images found a few things. Behaviour is consistent across browsers, which is great. 

We explicitly set that images under the tabnav component should be eager loaded, so it downloads all images, rendered or not. This can deff cause slowdown on slower/limited networks. 
Before this PR, it was not an issue, because the images are not rendered at all, compared to being hidden now.

If we however change the `imageLoadingStrategy` that back to `lazy`, browsers only load the images you can see. As you change the active tab, it starts downloading the ones on the new active tab.

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Review by hqhhuang — APPROVED** [review]
🚢

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Comment by hqhhuang** [comment]
@swift-ci test

**Pull request merged**
