### PR TITLE
Make sure that changing the language does not break the activePath tracking

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Bug/issue #, if applicable: 90843143

## Summary

Fixes errors when changing the page language.

Errors were caused by the `children` changing, but the `activeUID` that is stored was updated after the fact, when the RenderJSON gets updated, so we had a stale activeUID.

The fix is a simple guard, as the component handles the rest gradually.

## Dependencies

NA

## Testing

You need an archive that has a language variants and the `index`.

Steps:
1. Change the language
2. Assert it does not throw errors in the console.
3. Assert that navigating back and forth does not break anything.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Comment by ethan-kusters** [comment]
Attaching a small mixed-language DocC archive for testing here: [TinyMixedLanguageLibrary.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8367028/TinyMixedLanguageLibrary.doccarchive.zip).

**Review by marinaaisa — APPROVED** [review]
Thanks @dobromir-hristov and also @ethan-kusters for the doccarchive to test :)
I confirm that it's fixed 👏

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Pull request merged**
