### PR TITLE
Allow hiding available tags in NavigatorCard.vue

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Bug/issue #, if applicable: 100278813

## Summary

Allows hiding any available tags in the NavigatorCard search

## Dependencies

NA

## Testing

To test this you would need to extend the NavigatorCard and apply the `hideAvailableTags: true` prop.

Assert no tags are shown, no matter what navigator items you have.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Review by mportiz08 — APPROVED** [review]

**Review by mportiz08 — DISMISSED** [review]
Tests are failing but should be easy to fix. The implementation looks good.

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Comment by mportiz08** [comment]
@swift-ci test

**Review by mportiz08 — APPROVED** [review]

**Pull request merged**
