### PR TITLE
Fix uneven divider in nav bar for small viewport 

### PR DESCRIPTION
**Pull request by hqhhuang**
Bug/issue #, if applicable: 91372980

## Summary
Fix uneven divider in nav bar for the small viewport. This only happens when we use `NavMenuItem` component (not `NavMenuItems`
Fixed by overriding line height for the small viewport.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests - NA
- [x] Ran `npm test`, and it succeeded
- [ ] Updated documentation if necessary - NA

### CODE REVIEW

**Comment by hqhhuang** [comment]
@swift-ci test

**Review by dobromir-hristov — COMMENTED** [review]
This is the exact change that broke it. I am not sure whether we should revert that `min-height` to `height` or keep this fix. https://github.com/apple/swift-docc-render/pull/47/files#diff-0e3113fe0f5966efbcbf73dbccb8c910fd794de61da439d6063299dc39feee9cR46

I am OK with both. 

CC @marinaaisa

**Comment by marinaaisa** [comment]
> This is the exact change that broke it. I am not sure whether we should revert that `min-height` to `height` or keep this fix. https://github.com/apple/swift-docc-render/pull/47/files#diff-0e3113fe0f5966efbcbf73dbccb8c910fd794de61da439d6063299dc39feee9cR46
> 
> I am OK with both.
> 
> CC @marinaaisa

I don't have the context of why `height` was changed to `min-height` in the first place. If reverting it doesn't create a regression, I would prefer not adding new CSS. Since you were the one introducing the min-height change, can you tell if there is any regression when reverting it, @dobromir-hristov ?

**Comment by dobromir-hristov** [comment]
Not that i could see. I think it was so that we could have items larger than that height as children without cutoff.

**Comment by hqhhuang** [comment]
> Not that i could see. I think it was so that we could have items larger than that height as children without cutoff.

Do you have an example of that? I could open another PR and keep both `height` and `min-height`?

**Review by dobromir-hristov — APPROVED** [review]
I think I added the change, so that the links on the mobile Tutorial nav, are as height as they need to be, based on the amount of children they have. When it used to be a hard `height` it was going into a weird state where the children are visible, but the parent is only 42px.

The fix is OK, I will approve it.

**Comment by hqhhuang** [comment]
@swift-ci test

**Pull request merged**
