### PR TITLE
Add print-specific styling

### LINKED ISSUE #422: Improve the printed display of documentation pages
### Description

Currently, the print display of documentation webpages is suboptimal and could be improved.

Screenshot showing an example of the current suboptimal experience:
Screenshot 2022-08-23 at 2 57 07 PM

This might be a good first issue for someone new to Swift-DocC-Render who wants to help contribute in a straightforward but impactful way. :)

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc-render/issues).

### Expected Behavior

Interactive navigation elements like the sidebar and localnav/footer are not useful for print output and should probably be disabled using media queries.

### Actual behavior

All on-page elements are also included for print media, which is not always useful—especially for interactive navigation elements.

### Steps To Reproduce

1. Use any browser's "Print" functionality to preview the printable version of a documentation webpage.

### Swift-DocC-Render Version Information

bc7fe55e9c551b50978e77b3266cc58a90a1e6f5

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Bug/issue #, if applicable: 100868167, closes #422

## Summary

Adds print styles to the pages, mostly to hide dynamic navigation elements or fix issues when printing documentation.

**Notes:**
I could not for the life of me make some components not split up across pages. This happens when using `display:flex` or `display:grid`, which apparently is a common problem. For those cases its either make the entire container go to a new page, resulting in giant empty gaps, or just letting it get cutoff.

## Dependencies

NA

## Testing

Steps:
1. `Cmd + P` to print preview and assert how pages look
2. OnThisPage and Navigator are hidden intentionally, content is as wide as the page.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests
- [ ] Ran `npm test`, and it succeeded
- [ ] Updated documentation if necessary

### CODE REVIEW

**Review by SamLanier — APPROVED** [review]
Design approved.

**Comment by mportiz08** [comment]
Is this for #422 ?

**Comment by dobromir-hristov** [comment]
@mportiz08 will target that too as well, yes.

**Review by marinaaisa — APPROVED** [review]
Tested and looks good. Removing the sidebar on printing style helps a lot already. Thanks!

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Pull request merged**
