### PR TITLE
Shrink minimized mode border radius for Declaration, Code Listing, and Aside

### PR DESCRIPTION
**Pull request by hqhhuang**
Bug/issue #, if applicable: 104976416

## Summary
Shrink minimized mode border radius for Declaration, Code Listing, and Aside
Also did a slight refactor for CSS rules for minimized mode

## Testing
Steps:
1. Manually verify by navigating to any page with declaration, code listing, and aside.

### CODE REVIEW

**Review by dobromir-hristov — APPROVED** [review]
nice

**Comment by hqhhuang** [comment]
@swift-ci test

**Comment by hqhhuang** [comment]
@swift-ci test

**Comment by hqhhuang** [comment]
@swift-ci test

**Comment by hqhhuang** [comment]
@swift-ci test

**Pull request merged**
