### PR TITLE
LanguageToggle dropdown should have a cursor-pointer

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Bug/issue #, if applicable: 89923444

## Summary

Language toggle should have a pointer cursor icon.

## Dependencies

NA

## Testing

Open an archive that has language versions

Steps:
1. Assert that hovering over the language toggle shows a pointer cursor

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests
- [ ] Ran `npm test`, and it succeeded
- [ ] Updated documentation if necessary

### CODE REVIEW

**Comment by biamx3** [comment]
It's odd to me that when I hover over the "language:" label, the cursor doesn't switch to the hand but the language itself (like Swift) changes color to blue. 

Can you please make it so the color doesn't change when you hover the "language:" label? 

Also, since the chevron is part of the button, on hover, the cursor should also change to the hand and the language color should switch to blue.

**Comment by dobromir-hristov** [comment]
@biamx3 I fixed the pointer on the chevron, but not the blue color on label hover.

That looks like part of the general browser behaviour, as the label is linked to the dropdown, for accessibility reasons. Otherwise it wont be read out in VO when you focus on the dropdown.

**Comment by biamx3** [comment]
Got it, the accessibility aspect makes sense. With that in mind, I think we should make the label clickable as well as the language and chevron. So if I hover on top of any part of the component, the language label will turn to blue and the cursor will change to pointing hand. 

FYI, I tested the branch again today on Safari and Chrome and I'm not seeing the pointing hand cursor anymore – could be just me, but wanted to give you a heads up.

**Comment by dobromir-hristov** [comment]
Hey Bea, 

Cursor hand is still there, just tried it out.

However I have bad news about the clickable label. Turns out this is a browser limitation, and you cannot expand the select dropdown, when the user clicks on the label.

It should have already worked like that, but as you saw, it doesnt.

**Comment by biamx3** [comment]
> Cursor hand is still there, just tried it out.
Weird! I can't get it to show up for me anymore. 

> However I have bad news about the clickable label. Turns out this is a browser limitation, and you cannot expand the select dropdown, when the user clicks on the label.
I see... Bummer! Ok then, let's stick to the previous version where we have the pointing hand + blue label color on hover of the language (Swift) and chevron, and just the blue color on hover on the language (language) label.

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Pull request merged**
