### PR TITLE
[5.10] Remove rounding from device frame calculations

### PR DESCRIPTION
**Pull request by dobromir-hristov**
- Explanation: Removes the rounding from the DeviceFrames screen calcs, because they are causing weird rounding issues in browsers, while resizing.
- Scope: Device Frames
- Issue: rdar://115480995
- Risk: Low
- Testing: Tested manually and updated unit tests
- Reviewer: @marinaaisa  
- Original PR: https://github.com/apple/swift-docc-render/pull/750

### CODE REVIEW

**Review by franklinsch — APPROVED** [review]

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Review by franklinsch — APPROVED** [review]

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Pull request merged**
