### PR TITLE
Scroll to items as you navigate to them

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Bug/issue #, if applicable: 90601877

## Summary

Items should be scrolled into little by little, when focused, instead of jumping to the middle of the navigator scrollarea.

This is an alternative approach to #225 

## Dependencies

NA

## Testing

Steps:
1. Using keyboard arrows or VO, navigate up/down across the navigator.
2. Assert items are scrolled as you reach the bottom

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
I dont understand the issue.

**Comment by dobromir-hristov** [comment]
oh... yeah... that is a whole other can of worms

**Comment by biamx3** [comment]
This looks expected to me – feels natural. I'd leave it as is

**Review by marinaaisa — APPROVED** [review]
Approving in favor of https://github.com/apple/swift-docc-render/pull/225
Thanks Dobri 👏

**Pull request merged**
