### PR TITLE
Increase breakpoint for XL viewport

### PR DESCRIPTION
**Pull request by hqhhuang**
Bug/issue #, if applicable: 91308558

## Summary
We are increasing the width required to break into the XL viewport so that a 16inch MacBook Pro in full screen will stay in L viewport. 

## Testing
Steps:
1. Verify that no extra padding is added on either side of the content until the width of window is at least 1920 px.
2. Test that in XL viewport, default sidebar width is 543 px

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests - NA
- [x] Ran `npm test`, and it succeeded
- [ ] Updated documentation if necessary

### CODE REVIEW

**Comment by hqhhuang** [comment]
@swift-ci test

**Comment by hqhhuang** [comment]
@swift-ci test

**Review by dobromir-hristov — APPROVED** [review]
LGTM

**Comment by biamx3** [comment]
Looks good to me!

**Comment by hqhhuang** [comment]
@swift-ci test

**Pull request merged**
