### PR TITLE
Center the content for ultrawide

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Bug/issue #, if applicable: 100633732

## Summary

Change the be center aligned always, even on ultrawide. Changes the onThisPage nav container to match the new changes.

## Dependencies

NA

## Testing

Steps:
1.  Open the site on ultrawide
2. Assert the content is centered and the same size as before.
3. Assert that on any resolution, the content never overlaps the OnThisPage nav.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [ ] Updated documentation if necessary

### CODE REVIEW

**Comment by SamLanier** [comment]
@dobromir-hristov Is there a reason we keep a margin on both sides in XL viewports?

Screen Shot 2022-10-06 at 3 41 43 PM

**Comment by biamx3** [comment]
@SamLanier the goal of this change is to fix some animation issues we've had with the new sidebar button. Due to the way Safari works, if the content is left aligned in one view port and centered aligned in another, there's a weird animation jump and there's no way that we've found so far to fix it. 

rdar://100633732 (Navbar toggle animation “jumps” when bringing the navbar back)
rdar://100720563 (Sidebar: when dragging the sidebar back, there’s some jumping in the animation)

This is a relatively small change that's going to help deliver a lot of value with the new sidebar interaction. Also, I figured the content is going to look even more balanced anyways when we add the "On this page" component.

**Comment by SamLanier** [comment]
> @SamLanier the goal of this change is to fix some animation issues we've had with the new sidebar button. Due to the way Safari works, if the content is left aligned in one view port and centered aligned in another, there's a weird animation jump and there's no way that we've found so far to fix it.
> 
> rdar://100633732 (Navbar toggle animation “jumps” when bringing the navbar back) rdar://100720563 (Sidebar: when dragging the sidebar back, there’s some jumping in the animation)
> 
> This is a relatively small change that's going to help deliver a lot of value with the new sidebar interaction. Also, I figured the content is going to look even more balanced anyways when we add the "On this page" component.

Understood, I just wanted to know why there were margins in XL. Seems like we should use that space now that content in centered and the OTP element will be present.

**Comment by dobromir-hristov** [comment]
> @dobromir-hristov Is there a reason we keep a margin on both sides in XL viewports?

We have both a padding and a margin. The padding is to ensure that there is breathing room in the content, when say you make your navigator very wide, and the margin is just a way to tell the content to center itself.

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Comment by marinaaisa** [comment]
There is a padding left of 80px for the content's container that it feels unbalanced.
I suggest to turn it down to 22px as the OnThisPageStickyContainer's padding right.

Current:
Screenshot 2022-10-20 at 16 26 35

Suggestion:
Screenshot 2022-10-20 at 16 26 11

Thoughts @SamLanier ?
Note: We would need to adapt this margin to be the same on the content's container right when there is no On This Page

**Comment by dobromir-hristov** [comment]
Changed. @SamLanier please sign it off before we merge it. 

image
image

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Comment by SamLanier** [comment]
Spacing change does not look good when navigator is open, so let's leave the spacing as is.

**Comment by dobromir-hristov** [comment]
@marinaaisa can you take a final look at this please?

**Review by marinaaisa — APPROVED** [review]
LGTM!

**Pull request merged**
