### PR TITLE
Improve AX for code blocks

### PR DESCRIPTION
**Pull request by marinaaisa**
Bug/issue #105394505, if applicable: 

## Summary

Improve AX for code blocks:

For screen readers: it adds text telling when a code block starts and ends
For keyboard navigation users: it adds tabindex to code blocks to be able to scroll horizontally when focusing on them

## Dependencies

NA

## Testing

Steps:
1. Go to a page containing a code block, like in tutorials or declarations
2. Turn on VoiceOver and assert that it reads when a code block starts and ends
3. Turn off VoiceOver
4. Start tabbing until focusing on a code block that has a long line. Assert that by clicking on key arrows you can move to the right and left

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by marinaaisa** [comment]
@swift-ci test

**Review by dobromir-hristov — COMMENTED** [review]
I am not sure whether it makes sense to replace the tiny instances of `<code>` where its just used to wrap no more than 2-3 words, like in the `ParametersAttributes.

The change itself is fine.

**Comment by marinaaisa** [comment]
> I am not sure whether it makes sense to replace the tiny instances of `<code>` where its just used to wrap no more than 2-3 words, like in the `ParametersAttributes.
> 
> The change itself is fine.

Because it tells when a code block starts and ends, I believe it already adds value by its own

**Comment by marinaaisa** [comment]
After syncing with @dobromir-hristov I revert some implementation of CodeBlock component in irrelevant use cases. Please, @dobromir-hristov could you review again? Thanks!

**Comment by marinaaisa** [comment]
@swift-ci test

**Review by dobromir-hristov — COMMENTED** [review]
Did some testing and I think I dont see issues. I tested the CollapsibleCodeListing for a while as I was worried moving the `<code>` might cause issues, but its looks fine.

You have some unnecessary changes around, can you revert them?

@mportiz08 can you also look into this, just to be sure?

**Comment by marinaaisa** [comment]
> You have some unnecessary changes around, can you revert them?

Done!

**Comment by marinaaisa** [comment]
@swift-ci test

**Review by dobromir-hristov — APPROVED** [review]

**Comment by marinaaisa** [comment]
@swift-ci test

**Comment by marinaaisa** [comment]
@swift-ci test

**Pull request merged**
