### PR TITLE
Highlight unique components of overloaded declarations

### PR DESCRIPTION
**Pull request by mportiz08**
Bug/issue #, if applicable: 117503463

## Summary

Adds support for highlighting the unique components of overloaded declarations through a new, recursive declaration token component. These highlighted tokens will only be visually rendered when a group of overloaded symbols have been expanded by the user.

#### Example

Here, the highlights emphasize that this function is overloaded by the type of its only parameter.

Screenshot 2024-05-28 at 5 03 28 PM

## Dependencies

`swift-docc`: [Highlight declaration differences in overloaded symbol groups #928](https://github.com/apple/swift-docc/pull/928)

## Testing

Steps:
1. Checkout this branch and run `npm run build`
2. Checkout the branch of `swift-docc` from [this PR](https://github.com/apple/swift-docc/pull/928) and run `swift build`
3. Run `DOCC_HTML_DIR=/path/to/swift-docc-render/dist swift run docc preview --enable-experimental-overloaded-symbol-presentation Tests/SwiftDocCTests/Test\ Bundles/OverloadedSymbols.docc`
4. Verify that the unique parts of overloaded functions like the one in the above example are visually highlighted, only after disclosing the full list of the overloaded variants

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [X] Added tests
- [X] Ran `npm test`, and it succeeded
- [X] Updated documentation if necessary

\cc @QuietMisdreavus

### CODE REVIEW

**Comment by mportiz08** [comment]
@swift-ci test

**Comment by mportiz08** [comment]
Marking this as a draft, because it sounds like the swift-docc design for the Render JSON may change

**Review by marinaaisa — APPROVED** [review]
Tested and it works great!

**Comment by mportiz08** [comment]
Re-opening this, because it sounds like we're going to actually go with approach for now and later make the change to what is in #847 😅

**Comment by mportiz08** [comment]
@swift-ci test

**Pull request merged**
