### PR TITLE
Suggest only tags in the Navigator, that can return results

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Bug/issue #, if applicable: 89482723

## Summary

Change the navigator filter to only show tags, that have a match in the nav items

## Dependencies

NA

## Testing

Steps:
1. Open a page with the navigator
2. Click on the Nav filter
3. Assert the tags that are shown, only the ones we have content for. Based on on your archive, it may be all, some or even none.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Review by hqhhuang — APPROVED** [review]
Looks good! I'm surprised by how this actually didn't slow anything down visually.

**Review by hqhhuang — COMMENTED** [review]
Have you tested the performance in a bigger framework/technology, where there are a lot of children, but not all the types/tags? If so, how big was the framework?

**Comment by dobromir-hristov** [comment]
> Have you tested the performance in a bigger framework/technology, where there are a lot of children, but not all the types/tags? If so, how big was the framework?

I tried with 40k items, and I saw no change so far.

**Review by hqhhuang — APPROVED** [review]

**Comment by dobromir-hristov** [comment]
@swift-ci test

**Pull request merged**
