### PR TITLE
Update font size for hero

### PR DESCRIPTION
**Pull request by hqhhuang**
Bug/issue #, if applicable: rdar://123779770

## Summary
Change eyebrow font to `body-reduced` and add a new font `intro` for availability info.

## Testing
Test Manually

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests - NA
- [x] Ran `npm test`, and it succeeded 
- [ ] Updated documentation if necessary - NA

### CODE REVIEW

**Comment by hqhhuang** [comment]
@swift-ci test

**Review by marinaaisa — APPROVED** [review]
LGTM! 🚢

**Comment by marinaaisa** [comment]
@swift-ci test

**Comment by marinaaisa** [comment]
@swift-ci test

**Pull request merged**
